// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVDXYX1qKLvjLkyMCCjIE1N1soronBcaA',
    appId: '1:47155867274:web:733bc9a4544aa13efa0773',
    messagingSenderId: '47155867274',
    projectId: 'miniproject-1-aa936',
    authDomain: 'miniproject-1-aa936.firebaseapp.com',
    storageBucket: 'miniproject-1-aa936.appspot.com',
    measurementId: 'G-D5CEVS46RH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4Ex9Kk6s3yJ8cnDRemL57KS-Or8XF1IQ',
    appId: '1:47155867274:android:a987105ba17f33c1fa0773',
    messagingSenderId: '47155867274',
    projectId: 'miniproject-1-aa936',
    storageBucket: 'miniproject-1-aa936.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ1uAbDZmqZL_4WkB7NhGQqpt1_B85hD8',
    appId: '1:47155867274:ios:bf699a339fb1d682fa0773',
    messagingSenderId: '47155867274',
    projectId: 'miniproject-1-aa936',
    storageBucket: 'miniproject-1-aa936.appspot.com',
    iosBundleId: 'com.example.miniProject1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ1uAbDZmqZL_4WkB7NhGQqpt1_B85hD8',
    appId: '1:47155867274:ios:bf699a339fb1d682fa0773',
    messagingSenderId: '47155867274',
    projectId: 'miniproject-1-aa936',
    storageBucket: 'miniproject-1-aa936.appspot.com',
    iosBundleId: 'com.example.miniProject1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVDXYX1qKLvjLkyMCCjIE1N1soronBcaA',
    appId: '1:47155867274:web:204971def5c39df3fa0773',
    messagingSenderId: '47155867274',
    projectId: 'miniproject-1-aa936',
    authDomain: 'miniproject-1-aa936.firebaseapp.com',
    storageBucket: 'miniproject-1-aa936.appspot.com',
    measurementId: 'G-BH3NBVYN8R',
  );
}
